spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/realworld
    username: admin_dss
    password: 1234
  sql:
    init:
      mode: always
      schemaLocations: classpath:db/V1_create.sql
      dataLocations: classpath:db/dataSetup.sql

mybatis:
  mapperLocations: classpath:mapper/**/**.xml
  typeAliasesPackage: com.dss.realworld
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com:
      zaxxer:
        hikari: info
      dss:
        realworld: debug
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: trace
      sqlonly: OFF
      sqltiming: INFO
      connection : OFF

jwt:
  secret: DSS01ALLCHAN
  expirationTime: 604800000